assess posterior predictive distributions for game scores

- grab games
- grab old ratings (note date - date is in sim_league)
- look at games since then for which I have results
- for each game, make some sort of 2D plot of posterior
- add actual score
- devise some kind of test "statistic"


```{r}
library(tidyverse)
library(lubridate)
source("functions.R")
# source("../ratings/pred_next_functions.R")
```

grab

```{r}
games <- read_rds("../scoresway/rds/games.rds")
league_ids <- read_rds("../ratings/league_ids.rds")
last_dates <- get_lrdates()
league_info <- make_league_info(league_ids, last_dates)
```

input league by number

```{r}
this <- make_llist(league_info, 20, 2023)
this
```

extract games

```{r}
games_to_ppd <- extract_games_to_ppd(games, this)
games_to_ppd
```

get hold of ratings

```{r}
this$lc <- tolower(this$the_country)
fname <- str_c("../ratings/", this$lc, "_pre_post.rds")
read_rds(fname) %>% as.data.frame() -> posterior
prior_name <- str_c("../ratings/", this$lc, prior_year,"_prior.csv")
read_csv(prior_name) %>% 
  select(id, sw_id, name) -> prior
```


```{r}
games_to_ppd %>% 
  rowwise() %>% 
  mutate(stats = list(make_random_draws(posterior, prior, t1, t2, s1, s2))) %>% 
  mutate(min_stat = min(stats)) %>% 
  unnest_wider(stats) %>% 
  select(-t1, -t2) %>% 
  arrange(min_stat)
```







```{r}
compare_actual(randoms, actual[1], actual[2])
```

